---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: git-clone
  image: public.ecr.aws/prima/drone-git:1.3-3
  environment:
    PLUGIN_DEPTH: 5

- name: cache-restore
  image: public.ecr.aws/prima/drone-tools:1.21.0
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - cache-restore
  environment:
    BUCKET_NAME: prima-ci-cache
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint
  - name: docker
    path: /var/run/docker.sock
  - name: docker-conf
    path: /root/.docker
  depends_on:
  - git-clone

- name: check-secrets
  image: public.ecr.aws/prima/drone-tools:1.21.0
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - check-secrets-grants
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint
  depends_on:
  - git-clone

- name: check-public-docker-images
  image: public.ecr.aws/prima/drone-tools:1.21.0
  commands:
  - check-public-docker-images
  depends_on:
  - git-clone

- name: build-image
  image: public.ecr.aws/prima/drone-tools:1.21.0
  commands:
  - sed -i 's/USER node/USER root/g' ./Dockerfile
  - docker build -t prima/pyxis-react-ci:${DRONE_COMMIT} ./
  volumes:
  - name: docker
    path: /var/run/docker.sock
  - name: docker-conf
    path: /root/.docker
  depends_on:
  - cache-restore

- name: dependencies
  image: prima/pyxis-react-ci:${DRONE_COMMIT}
  commands:
  - yarn
  environment:
    YARN_CACHE_FOLDER: /drone/src/.cache/yarn
  depends_on:
  - build-image

- name: lint
  image: prima/pyxis-react-ci:${DRONE_COMMIT}
  commands:
  - yarn lint
  environment:
    YARN_CACHE_FOLDER: /drone/src/.cache/yarn
  depends_on:
  - dependencies

- name: build
  image: prima/pyxis-react-ci:${DRONE_COMMIT}
  commands:
  - yarn build
  environment:
    YARN_CACHE_FOLDER: /drone/src/.cache/yarn
  depends_on:
  - lint

- name: storybook
  image: prima/pyxis-react-ci:${DRONE_COMMIT}
  commands:
  - yarn storybook:build
  environment:
    YARN_CACHE_FOLDER: /drone/src/.cache/yarn
  depends_on:
  - build

- name: sassdocs
  image: prima/pyxis-react-ci:${DRONE_COMMIT}
  commands:
  - yarn sassdocs:build
  environment:
    YARN_CACHE_FOLDER: /drone/src/.cache/yarn
  depends_on:
  - build

- name: cache-save
  image: public.ecr.aws/prima/drone-tools:1.21.0
  commands:
  - . /etc/profile.d/ecs-credentials-endpoint
  - cache-save .cache node_modules
  environment:
    BUCKET_NAME: prima-ci-cache
  volumes:
  - name: ecs
    path: /etc/profile.d/ecs-credentials-endpoint
  - name: docker
    path: /var/run/docker.sock
  - name: docker-conf
    path: /root/.docker
  when:
    branch:
    - master
  depends_on:
  - dependencies
  - lint
  - build
  - storybook
  - sassdocs

volumes:
- name: docker
  host:
    path: /var/run/docker.sock
- name: ecs
  host:
    path: /etc/profile.d/ecs-credentials-endpoint
- name: docker-conf
  host:
    path: /home/ec2-user/.docker

trigger:
  event:
  - push

---
kind: pipeline
name: email-failure

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: email-failure
  image: public.ecr.aws/prima/drone-email
  settings:
    from: drone@prima.it
    host: email-smtp.eu-west-1.amazonaws.com
  environment:
    PLUGIN_PASSWORD:
      from_secret: email_password
    PLUGIN_USERNAME:
      from_secret: email_username

trigger:
  status:
  - failure
  target:
    exclude:
    - qa-stack
    - qa-it
    - qa

depends_on:
- default

---
kind: signature
hmac: 711ffc2c4978b9d06b1162a2c7777f88a9d477a63d7e2682d3a012c53c73208f

...
